### ISSUE TITLE
Exercising my right to retract over all my contributions

### ISSUE THREAD

**Issue by akarysbutagain** [QuiltMC/art#19]
# Foreword

The French intellectual property code gives an inalienable right to authors to retract:
> Nonobstant la cession de son droit d'exploitation, l'auteur, même postérieurement à la publication de son oeuvre, jouit d'un droit de repentir ou de retrait vis-à-vis du cessionnaire. Il ne peut toutefois exercer ce droit qu'à charge d'indemniser préalablement le cessionnaire du préjudice que ce repentir ou ce retrait peut lui causer. Lorsque, postérieurement à l'exercice de son droit de repentir ou de retrait, l'auteur décide de faire publier son oeuvre, il est tenu d'offrir par priorité ses droits d'exploitation au cessionnaire qu'il avait originairement choisi et aux conditions originairement déterminées.

\- Article L121-4 - Code de la propriété intellectuelle

# Request

I (@Akarys42 / @simpledemonn) would like to exercise my rights on all my applicable contributions, including but not limited to:
- New pride banner design (https://github.com/QuiltMC/art/pull/13)
- Add the pluralapple emote (https://github.com/QuiltMC/art/pull/7)

# Discussion

This right being inalieably granted to me, you may not oppose by any way to this request. Any previous license or agreement is null and void under the law. You do not possess any legal basis to continue using, reproducing, modifying or exploiting any of my work.

**You are not permitted to use my artwork in any way.** This applies to any work that I could have produced that is not stored inside this repository. 

If this request is not followed, we will move for enforcement 14 days after this issue has been opened.

**Comment by gdude2002** [comment]
I'd like to point out that the pride banner cannot reasonably be considered your work - it's a modified version of my pride banner, with the triangles from the Progress flag removed, and even appears to use precisely the same positioning for the background flag - and the rainbow flag isn't a design that belongs to either of us.

Otherwise, it's correct that French "moral rights" allow a creator to have their work removed, even after it enters the public domain - so, even if this issue is petty, once someone can actually confirm that this account is real and not just a sock-puppet created by a troll, I'd recommend honouring the request.

**Comment by gdude2002** [comment]
> I'd like to point out that the pride banner cannot reasonably be considered your work
Yeah, having just compared the project file in your PR against the version that was there before, your submitted copy is simply my project file with some layers turned off.

![image](https://github.com/user-attachments/assets/d2eab135-67b2-4bb6-9cab-c264de2b6586)

**Comment by OroArmor** [comment]
Followed with commit 849d6df

**Comment by gdude2002** [comment]
In line with https://github.com/QuiltMC/art/commit/849d6dfd9ba639895e15c7b200e06b3bb50e9c2e, I've ensured the emoji was also removed from the Discord servers.

![image](https://github.com/user-attachments/assets/d82a1a2b-beea-40cf-a652-981434211394)
